.TH "headers Directory Reference" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAction\&.h\fP"
.br
.RI "Contains all structures related to actions on element\&. "
.ti -1c
.RI "file \fBClickable\&.h\fP"
.br
.RI "Generic hitboxes either polygonial, elliptic or a mixe of both\&. "
.ti -1c
.RI "file \fBDisplayCode\&.h\fP"
.br
.RI "Contains display code and list of display codes\&. "
.ti -1c
.RI "file \fBElement\&.h\fP"
.br
.RI "Contains all structures related to Elements\&. "
.ti -1c
.RI "file \fBFont\&.h\fP"
.br
.RI "Information about TTF objects\&. "
.ti -1c
.RI "file \fBSANDAL2\&.h\fP"
.br
.RI "\fBSANDAL2\&.h\fP is the file to include which includes everything else\&. Compilation flags to use : -lSDL2 -lSDL2_ttf -lSDL2_image -lm\&. "
.ti -1c
.RI "file \fBSprite\&.h\fP"
.br
.RI "\fBSprite\fP manager for SANDAL2\&. "
.ti -1c
.RI "file \fBWindow\&.h\fP"
.br
.RI "Contains all structures related to windows but only those unrelated to Elements\&. "
.in -1c
