.TH "ActionNode" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionNode
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBAction\fP \fBaction\fP"
.br
.ti -1c
.RI "   \fBListAction\fP \fBlist\fP"
.br
.ti -1c
.RI "} \fBaction\fP"
.br
.ti -1c
.RI "int \fBisList\fP"
.br
.ti -1c
.RI "int \fBisFinished\fP"
.br
.ti -1c
.RI "struct \fBActionNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "union { \&.\&.\&. }   ActionNode::action"
action of the node (either an actual action or a list of actions) 
.SS "int ActionNode::isFinished"
tells whether or not the node is finished 
.SS "int ActionNode::isList"
tells whether the node is an actual action or a list of actions 
.SS "struct \fBActionNode\fP* ActionNode::next"
next node of the action list 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
