.TH "Circle" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circle \- Represente a hittable ellipse\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Clickable\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCircle\fP * \fBnext\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBrY\fP"
.br
.ti -1c
.RI "float \fBrX\fP"
.br
.ti -1c
.RI "float \fBtheta\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represente a hittable ellipse\&. 
.SH "Member Data Documentation"
.PP 
.SS "struct \fBCircle\fP* Circle::next"
next ellipse 
.SS "float Circle::rX"
size of the radius parallel to the abscissa axis 
.SS "float Circle::rY"
size of the radius parallel to the ordinate axis 
.SS "float Circle::theta"
degree of rotation 
.SS "float Circle::x"
abscissa coordinate of the center of the ellipse 
.SS "float Circle::y"
ordinate coordinate of the center of the ellipse 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
