.TH "Clickable" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clickable \- Represente a hit boxe which is a collection of \fBLine\fP (defining a convexe polygon) and \fBCircle\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Clickable\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLine\fP * \fBfirstL\fP"
.br
.ti -1c
.RI "\fBCircle\fP * \fBfirstC\fP"
.br
.ti -1c
.RI "struct \fBClickable\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represente a hit boxe which is a collection of \fBLine\fP (defining a convexe polygon) and \fBCircle\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBCircle\fP* Clickable::firstC"
first element of the ellipses' list 
.SS "\fBLine\fP* Clickable::firstL"
first element of the lines' list 
.SS "struct \fBClickable\fP* Clickable::next"
next hitbox 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
