.TH "DisplayCode" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisplayCode \- Display code containing the plan and a flag to indicate if it is displaied\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DisplayCode\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBDisplayCode\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "int \fBisDisplaied\fP"
.br
.ti -1c
.RI "int \fBplan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Display code containing the plan and a flag to indicate if it is displaied\&. 
.SH "Member Data Documentation"
.PP 
.SS "int DisplayCode::code"
display code 
.SS "int DisplayCode::isDisplaied"
flag to tell whether or not the element should be displaied 
.SS "struct \fBDisplayCode\fP* DisplayCode::next"
next \fBDisplayCode\fP 
.SS "int DisplayCode::plan"
plan linked to the display code 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
