.TH "EventElement" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventElement \- Behaviors of an element to events\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Element\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBaction\fP )(struct \fBElement\fP *)"
.br
.ti -1c
.RI "void(* \fBonClick\fP )(struct \fBElement\fP *, int)"
.br
.ti -1c
.RI "void(* \fBunClick\fP )(struct \fBElement\fP *, int)"
.br
.ti -1c
.RI "void(* \fBkeyPress\fP )(struct \fBElement\fP *, SDL_Keycode c)"
.br
.ti -1c
.RI "void(* \fBkeyReleased\fP )(struct \fBElement\fP *, SDL_Keycode c)"
.br
.ti -1c
.RI "void(* \fBunSelect\fP )(struct \fBElement\fP *)"
.br
.ti -1c
.RI "void(* \fBendSprite\fP )(struct \fBElement\fP *, int code)"
.br
.ti -1c
.RI "void(* \fBonMouseMotion\fP )(struct \fBElement\fP *)"
.br
.ti -1c
.RI "void(* \fBunMouseMotion\fP )(struct \fBElement\fP *)"
.br
.ti -1c
.RI "void(* \fBendAction\fP )(struct \fBElement\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Behaviors of an element to events\&. 
.SH "Member Data Documentation"
.PP 
.SS "void(* EventElement::action) (struct \fBElement\fP *)"
function called when update 
.SS "void(* EventElement::endAction) (struct \fBElement\fP *)"
function called when the \fBListAction\fP bound to the element (if any) ends 
.SS "void(* EventElement::endSprite) (struct \fBElement\fP *, int code)"
function called at the end of a sprite 
.SS "void(* EventElement::keyPress) (struct \fBElement\fP *, SDL_Keycode c)"
function called when a key is pressed 
.SS "void(* EventElement::keyReleased) (struct \fBElement\fP *, SDL_Keycode c)"
function called when a key is released 
.SS "void(* EventElement::onClick) (struct \fBElement\fP *, int)"
function called when the element is clicked 
.SS "void(* EventElement::onMouseMotion) (struct \fBElement\fP *)"
function called when the mouse move over a zone 
.SS "void(* EventElement::unClick) (struct \fBElement\fP *, int)"
function called when the element is unclicked 
.SS "void(* EventElement::unMouseMotion) (struct \fBElement\fP *)"
function called when the mouse exit the hover zone 
.SS "void(* EventElement::unSelect) (struct \fBElement\fP *)"
function called when the element is unselected 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
