.TH "Line" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line \- Represente a line which delimitate a hittable surface from a none hittable one\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Clickable\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBLine\fP * \fBnext\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBc\fP"
.br
.ti -1c
.RI "int \fBside\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represente a line which delimitate a hittable surface from a none hittable one\&. 
.SH "Member Data Documentation"
.PP 
.SS "float Line::a"
a in the equation of the line ax+by=c 
.SS "float Line::b"
b in the equation of the line ax+by=c 
.SS "float Line::c"
c in the equation of the line ax+by=c 
.SS "struct \fBLine\fP* Line::next"
next element 
.SS "int Line::side"
side of the line that is hittable (-1 : ax+by<c, 1 : ax+by>c) 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
