.TH "ListAction" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListAction
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBActionNode\fP * \fBfirst\fP"
.br
.ti -1c
.RI "int \fBisParallel\fP"
.br
.ti -1c
.RI "int \fBisForever\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBActionNode\fP* ListAction::first"
first node of the action list 
.SS "int ListAction::isForever"
flag to tell if the action list needs to run forever 
.SS "int ListAction::isParallel"
tells whether or not this list is the starting point of a parallel list 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
