.TH "ListClickable" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListClickable \- Collection of hit boxes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Clickable\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBClickable\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBClickable\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "\fBClickable\fP * \fBfirstBlock\fP"
.br
.ti -1c
.RI "\fBClickable\fP * \fBcurrentBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Collection of hit boxes\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBClickable\fP* ListClickable::current"
Current hit box of the list 
.SS "\fBClickable\fP* ListClickable::currentBlock"
Current blocking hit box of the list 
.SS "\fBClickable\fP* ListClickable::first"
First hit box of the list 
.SS "\fBClickable\fP* ListClickable::firstBlock"
First blocking hit box of the list 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
