.TH "ListAnimation" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListAnimation \- a list of animations  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sprite\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBListSprite\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBListSprite\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "unsigned \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a list of animations 
.SH "Member Data Documentation"
.PP 
.SS "\fBListSprite\fP* ListAnimation::current"
current animation 
.SS "\fBListSprite\fP* ListAnimation::first"
first animation 
.SS "unsigned ListAnimation::size"
number of animations 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
