.TH "ListDCElement" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListDCElement \- List (display code) of list (plan) of element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Element\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBListPtrElement\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBListPtrElement\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "struct \fBListDCElement\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List (display code) of list (plan) of element\&. 
.SH "Member Data Documentation"
.PP 
.SS "int ListDCElement::code"
display code of this list 
.SS "\fBListPtrElement\fP* ListDCElement::current"
current list (plan) of element (used for iterator) 
.SS "\fBListPtrElement\fP* ListDCElement::first"
first list (plan) of element 
.SS "struct \fBListDCElement\fP* ListDCElement::next"
next list (display code) of list (plan) of element 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
