.TH "ListElement" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListElement \- List of list (display code) of list (plan) of elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Element\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBListDCElement\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBListDCElement\fP * \fBcurrentDCIterator\fP"
.br
.ti -1c
.RI "\fBListPtrElement\fP * \fBcurrentPIterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of list (display code) of list (plan) of elements\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBListDCElement\fP* ListElement::currentDCIterator"
current list (display code) of list (plan) of elements (used for iterator) 
.SS "\fBListPtrElement\fP* ListElement::currentPIterator"
current list (plan) of elements (used for iterator) 
.SS "\fBListDCElement\fP* ListElement::first"
first list (display code) of list (plan) of elements 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
