.TH "ListDisplayCode" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListDisplayCode \- List of display codes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DisplayCode\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDisplayCode\fP * \fBfirst\fP"
.br
.ti -1c
.RI "unsigned \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of display codes\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBDisplayCode\fP* ListDisplayCode::first"
first element of the list 
.SS "unsigned ListDisplayCode::size"
size of the list 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
