.TH "ListWindow" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListWindow \- list of windows  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Window\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindow\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBWindow\fP * \fBlast\fP"
.br
.ti -1c
.RI "\fBWindow\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "\fBWindow\fP * \fBcurrentDisplay\fP"
.br
.ti -1c
.RI "unsigned \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
list of windows 
.SH "Member Data Documentation"
.PP 
.SS "unsigned ListWindow::count"
number of windows currently opened in the list 
.SS "\fBWindow\fP* ListWindow::current"
current \fBWindow\fP of the list 
.SS "\fBWindow\fP* ListWindow::currentDisplay"
current \fBWindow\fP displaied of the list 
.SS "\fBWindow\fP* ListWindow::first"
First \fBWindow\fP of the list 
.SS "\fBWindow\fP* ListWindow::last"
Last \fBWindow\fP of the list 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
