.TH "PtrElement" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PtrElement \- Structure used to store elements' pointers in a list of element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Element\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBElement\fP * \fBelement\fP"
.br
.ti -1c
.RI "struct \fBPtrElement\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBdeleted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store elements' pointers in a list of element\&. 
.SH "Member Data Documentation"
.PP 
.SS "int PtrElement::deleted"
tells whether or not this \fBPtrElement\fP should be deleted 
.SS "\fBElement\fP* PtrElement::element"
pointer of the element 
.SS "struct \fBPtrElement\fP* PtrElement::next"
next \fBPtrElement\fP in the list 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
