.TH "Sprite" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite \- informations about a step of an animation  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sprite\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBSprite\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBSprite\fP * \fBprev\fP"
.br
.ti -1c
.RI "int \fBcoords\fP [4]"
.br
.ti -1c
.RI "unsigned \fBlifespan\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
informations about a step of an animation 
.SH "Member Data Documentation"
.PP 
.SS "int Sprite::code"
identifier of the \fBSprite\fP 
.SS "int Sprite::coords[4]"
[0] and [1] for the coordinates of the top left corner and [2] and [3] respectively for the width and the height 
.SS "unsigned Sprite::lifespan"
number of time minus one the \fBSprite\fP should be displaied before going to the next 
.SS "struct \fBSprite\fP* Sprite::next"
next step of the animation 
.SS "struct \fBSprite\fP* Sprite::prev"
previous step of the animation 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
