.TH "Window" 3 "Sun Jun 2 2019" "SANDAL2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window \- SANDAL2 window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Window\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBinitHeight\fP"
.br
.ti -1c
.RI "int \fBinitWidth\fP"
.br
.ti -1c
.RI "int \fBdisplayCode\fP"
.br
.ti -1c
.RI "int \fBbackground\fP [4]"
.br
.ti -1c
.RI "int \fBorigin\fP [2]"
.br
.ti -1c
.RI "SDL_Window * \fBwindow\fP"
.br
.ti -1c
.RI "SDL_Renderer * \fBrenderer\fP"
.br
.ti -1c
.RI "struct \fBListElement\fP * \fBliste\fP"
.br
.ti -1c
.RI "\fBEventWindow\fP \fBevents\fP"
.br
.ti -1c
.RI "struct \fBWindow\fP * \fBnext\fP"
.br
.ti -1c
.RI "unsigned \fBtoDelete\fP"
.br
.ti -1c
.RI "int \fBclose\fP"
.br
.ti -1c
.RI "int \fBnewDisplayCode\fP"
.br
.ti -1c
.RI "int \fBdisplayToChange\fP"
.br
.ti -1c
.RI "struct \fBListDCElement\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "int \fBstop\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "int \fBfocused\fP"
.br
.ti -1c
.RI "Uint32 \fBticks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SANDAL2 window\&. 
.SH "Member Data Documentation"
.PP 
.SS "int Window::background[4]"
background color of the window 
.SS "int Window::close"
tells whether or not the window should be closed 
.SS "struct \fBListDCElement\fP* Window::current"
current list of elements to display 
.SS "void* Window::data"
data of the window 
.SS "int Window::displayCode"
display code of the window 
.SS "int Window::displayToChange"
tells whether or not the display code has to be changed 
.SS "\fBEventWindow\fP Window::events"
behavior of the window to events 
.SS "int Window::focused"
tells whether or not the window is focused 
.SS "int Window::height"
current height of the window 
.SS "int Window::initHeight"
initial height of the window 
.SS "int Window::initWidth"
initial width of the window 
.SS "struct \fBListElement\fP* Window::liste"
elements in the window 
.SS "int Window::newDisplayCode"
display code to be changed 
.SS "struct \fBWindow\fP* Window::next"
next window 
.SS "int Window::origin[2]"
origin of the window (initialized at (0,0)) 
.SS "SDL_Renderer* Window::renderer"
renderer 
.SS "int Window::state"
tells if window is in full screen or normal 
.SS "int Window::stop"
tells whether or not all elements where removed 
.SS "Uint32 Window::ticks"
ticks since last update call 
.SS "unsigned Window::toDelete"
number of element to be deleted by the cleaner 
.SS "int Window::width"
current width of the window 
.SS "SDL_Window* Window::window"
true window 

.SH "Author"
.PP 
Generated automatically by Doxygen for SANDAL2 from the source code\&.
